<?php

namespace Laragento\CatalogUrlRewrite\Models;

use Illuminate\Database\Eloquent\Model;

//@todo duplicate model

/**
 * Class UrlRewrite
 *
 * @package Laragento\CatalogUrlRewrite\Models
 * @property string entity_type
 * @property int entity_id
 * @property string request_path
 * @property string target_path
 * @property int redirect_type
 * @property int store_id
 * @property string description
 * @property int is_autogenerated
 * @property string metadata
 * @property int $url_rewrite_id Rewrite Id
 * @property string $entity_type Entity type code
 * @property int $entity_id Entity ID
 * @property string|null $request_path Request Path
 * @property string|null $target_path Target Path
 * @property int $redirect_type Redirect Type
 * @property int $store_id Store Id
 * @property string|null $description Description
 * @property int $is_autogenerated Is rewrite generated automatically flag
 * @property string|null $metadata Meta data for url rewrite
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\CatalogUrlRewrite\Models\UrlRewrite whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\CatalogUrlRewrite\Models\UrlRewrite whereEntityId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\CatalogUrlRewrite\Models\UrlRewrite whereEntityType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\CatalogUrlRewrite\Models\UrlRewrite whereIsAutogenerated($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\CatalogUrlRewrite\Models\UrlRewrite whereMetadata($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\CatalogUrlRewrite\Models\UrlRewrite whereRedirectType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\CatalogUrlRewrite\Models\UrlRewrite whereRequestPath($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\CatalogUrlRewrite\Models\UrlRewrite whereStoreId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\CatalogUrlRewrite\Models\UrlRewrite whereTargetPath($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\CatalogUrlRewrite\Models\UrlRewrite whereUrlRewriteId($value)
 * @mixin \Eloquent
 */
class UrlRewrite extends Model
{
    protected $table = 'url_rewrite';
    protected $fillable = [
        'entity_type',
        'entity_id',
        'request_path',
        'target_path',
        'redirect_type',
        'store_id',
        'description',
        'is_autogenerated',
        'metadata',
    ];
    protected $primaryKey = 'url_rewrite_id';
    public $timestamps = false;
}