<?php

namespace Laragento\Catalog\Models\Url;

use Illuminate\Database\Eloquent\Model;

//@todo duplicate model

class UrlRewrite extends Model
{
    protected $table = 'url_rewrite';
    protected $fillable = [
        'url_rewrite_id',
        'entity_type',
        'entity_id',
        'request_path',
        'target_path',
        'redirect_type',
        'store_id',
        'description',
        'is_autogenerated',
        'metadata',
    ];
    protected $primaryKey = 'url_rewrite_id';
}