<?php

namespace Laragento\Catalog\Models\Url;

use Illuminate\Database\Eloquent\Model;

//@todo duplicate model

/**
 * Laragento\Catalog\Models\Url\UrlRewrite
 *
 * @property int $url_rewrite_id Rewrite Id
 * @property string $entity_type Entity type code
 * @property int $entity_id Entity ID
 * @property string|null $request_path Request Path
 * @property string|null $target_path Target Path
 * @property int $redirect_type Redirect Type
 * @property int $store_id Store Id
 * @property string|null $description Description
 * @property int $is_autogenerated Is rewrite generated automatically flag
 * @property string|null $metadata Meta data for url rewrite
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\Catalog\Models\Url\UrlRewrite whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\Catalog\Models\Url\UrlRewrite whereEntityId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\Catalog\Models\Url\UrlRewrite whereEntityType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\Catalog\Models\Url\UrlRewrite whereIsAutogenerated($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\Catalog\Models\Url\UrlRewrite whereMetadata($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\Catalog\Models\Url\UrlRewrite whereRedirectType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\Catalog\Models\Url\UrlRewrite whereRequestPath($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\Catalog\Models\Url\UrlRewrite whereStoreId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\Catalog\Models\Url\UrlRewrite whereTargetPath($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\Laragento\Catalog\Models\Url\UrlRewrite whereUrlRewriteId($value)
 * @mixin \Eloquent
 */
class UrlRewrite extends Model
{
    protected $table = 'url_rewrite';
    protected $fillable = [
        'url_rewrite_id',
        'entity_type',
        'entity_id',
        'request_path',
        'target_path',
        'redirect_type',
        'store_id',
        'description',
        'is_autogenerated',
        'metadata',
    ];
    protected $primaryKey = 'url_rewrite_id';
}