<?php

namespace Laragento\CatalogUrlRewrite\Models;

use Illuminate\Database\Eloquent\Model;

//@todo duplicate model

/**
 * Class UrlRewrite
 * @package Laragento\CatalogUrlRewrite\Models
 * @property string entity_type
 * @property int entity_id
 * @property string request_path
 * @property string target_path
 * @property int redirect_type
 * @property int store_id
 * @property string description
 * @property int is_autogenerated
 * @property string metadata
 */
class UrlRewrite extends Model
{
    protected $table = 'url_rewrite';
    protected $fillable = [
        'entity_type',
        'entity_id',
        'request_path',
        'target_path',
        'redirect_type',
        'store_id',
        'description',
        'is_autogenerated',
        'metadata',
    ];
    protected $primaryKey = 'url_rewrite_id';
    public $timestamps = false;
}